listen_address = "0.0.0.0:9252"
concurrent = 20
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 600

[[runners]]
  name = "runner.example.org/docker/share/01/gitlab.com/example-org"
  limit = 15
  request_concurrency = 15
  url = "https://gitlab.com/"
  id = 01234567
  token = "********************"
  token_obtained_at = 2023-05-07T11:17:27Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "docker:23.0.5"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0

[[runners]]
  name = "runner.example.org/shell/example-org/01/gitlab.com/example-org"
  limit = 5
  request_concurrency = 5
  url = "https://gitlab.com/"
  id = 01234568
  token = "********************"
  token_obtained_at = 2023-05-07T11:17:27Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.cache]
    MaxUploadedArchiveSize = 0
